import type { Metadata } from "next";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Windless Technologies.",
  alternates: { canonical: "/privacy" },
  robots: { index: true, follow: true },
};

const sectionClass = "mt-10";
const hClass = "font-display text-2xl font-semibold text-ink-primary";
const pClass = "mt-3 text-ink-secondary leading-relaxed";
const listClass = "mt-3 space-y-2 text-ink-secondary leading-relaxed list-disc pl-5";

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main id="main">
        <section className="max-w-3xl mx-auto px-6 py-16 sm:py-20">
          <p className="font-mono text-xs uppercase tracking-widest text-blueprint">
            Legal
          </p>
          <h1 className="mt-3 font-display text-4xl font-semibold text-ink-primary">
            Privacy Policy
          </h1>
          <p className="mt-3 text-sm text-ink-muted">Last updated: February 5, 2025</p>

          <p className={pClass}>
            This Privacy Policy describes Our policies and procedures on the
            collection, use, and disclosure of Your information when You use
            the Service, and tells You about Your privacy rights and how the
            law protects You.
          </p>
          <p className={pClass}>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>

          <section className={sectionClass}>
            <h2 className={hClass}>Interpretation &amp; Definitions</h2>
            <h3 className="mt-5 font-display text-lg font-semibold text-ink-primary">
              Interpretation
            </h3>
            <p className={pClass}>
              Words with an initial capital letter have meanings defined
              under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear
              in singular or in plural.
            </p>
            <h3 className="mt-5 font-display text-lg font-semibold text-ink-primary">
              Definitions
            </h3>
            <ul className={listClass}>
              <li>
                <strong className="text-ink-primary">Account</strong> means a
                unique account created for You to access our Service or
                parts of our Service.
              </li>
              <li>
                <strong className="text-ink-primary">Company</strong>{" "}
                (referred to as either &quot;the Company&quot;,
                &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot; in this
                Agreement) refers to Windless Technologies.
              </li>
              <li>
                <strong className="text-ink-primary">Cookies</strong> are
                small files placed on Your computer, mobile device, or any
                other device by a website, containing details of Your
                browsing history among its many uses.
              </li>
              <li>
                <strong className="text-ink-primary">Country</strong> refers
                to: United States.
              </li>
              <li>
                <strong className="text-ink-primary">Device</strong> means
                any device that can access the Service, such as a computer,
                a cellphone, or a digital tablet.
              </li>
              <li>
                <strong className="text-ink-primary">Personal Data</strong>{" "}
                is any information that relates to an identified or
                identifiable individual.
              </li>
              <li>
                <strong className="text-ink-primary">Service</strong> refers
                to the website, provided by Windless Technologies.
              </li>
              <li>
                <strong className="text-ink-primary">Service Provider</strong>{" "}
                means any natural or legal person who processes the data on
                behalf of the Company - third-party companies or individuals
                employed by the Company to facilitate the Service, provide
                the Service on behalf of the Company, perform services
                related to the Service, or assist the Company in analyzing
                how the Service is used.
              </li>
              <li>
                <strong className="text-ink-primary">Usage Data</strong>{" "}
                refers to data collected automatically, either generated by
                the use of the Service or from the Service infrastructure
                itself (for example, the duration of a page visit).
              </li>
              <li>
                <strong className="text-ink-primary">You</strong> means the
                individual accessing or using the Service, or the company,
                or other legal entity on behalf of which such individual is
                accessing or using the Service, as applicable.
              </li>
            </ul>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Collecting &amp; Using Your Personal Data</h2>

            <h3 className="mt-5 font-display text-lg font-semibold text-ink-primary">
              Types of Data Collected
            </h3>
            <p className={pClass}>
              <strong className="text-ink-primary">Personal Data.</strong>{" "}
              While using Our Service, We may ask You to provide certain
              personally identifiable information, including but not limited
              to: your name and contact information; payment information
              processed by third parties; and details about your project
              submitted through our contact form.
            </p>
            <p className={pClass}>
              <strong className="text-ink-primary">Usage Data.</strong> Usage
              Data is collected automatically when using the Service and may
              include information such as Your Device&apos;s IP address,
              browser type, browser version, the pages of our Service that
              You visit, the time and date of Your visit, the time spent on
              those pages, and other diagnostic data.
            </p>
            <p className={pClass}>
              <strong className="text-ink-primary">
                Tracking Technologies &amp; Cookies.
              </strong>{" "}
              We use Cookies and similar tracking technologies to track
              activity on Our Service and store certain information. These
              may include essential cookies (necessary for the Service to
              function), preference cookies (to remember Your choices), and
              analytics cookies (to understand how the Service is used).
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Use of Your Personal Data</h2>
            <p className={pClass}>The Company may use Personal Data for the following purposes:</p>
            <ul className={listClass}>
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account and Your relationship with us as a user of the Service.</li>
              <li>To process and manage project deliverables and payments.</li>
              <li>To contact You by email, telephone, or other equivalent forms of electronic communication.</li>
              <li>To improve our Service based on how You use it.</li>
              <li>To comply with a legal obligation.</li>
            </ul>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Sharing Your Personal Data</h2>
            <p className={pClass}>
              We do not sell Your Personal Data. We may share Your personal
              information in the following situations: with Service
              Providers who process data on Our behalf; when required to
              comply with a legal obligation; and in connection with a
              merger, sale of Company assets, financing, or acquisition of
              all or a portion of Our business.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Retention &amp; Security of Your Personal Data</h2>
            <p className={pClass}>
              The Company will retain Your Personal Data only for as long as
              is necessary for the purposes set out in this Privacy Policy,
              and to the extent necessary to comply with our legal
              obligations, resolve disputes, and enforce our agreements. The
              security of Your Personal Data is important to Us, but no
              method of transmission over the Internet or method of
              electronic storage is 100% secure.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Your Rights</h2>
            <p className={pClass}>
              Depending on Your location, You may have the right to access,
              update, or delete the information We have on You, and to
              opt-out of certain uses of Your Personal Data. You can
              exercise these rights by contacting Us using the information
              below.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Children&apos;s Privacy</h2>
            <p className={pClass}>
              Our Service is not intended for use by children under the age
              of 13. We do not knowingly collect personally identifiable
              information from anyone under the age of 13. If You are a
              parent or guardian and You are aware that Your child has
              provided Us with Personal Data, please contact Us.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Changes to this Privacy Policy</h2>
            <p className={pClass}>
              We may update Our Privacy Policy from time to time. We will
              notify You of any changes by posting the new Privacy Policy on
              this page and updating the &quot;Last updated&quot; date at
              the top of this Privacy Policy.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={hClass}>Contact Us</h2>
            <p className={pClass}>
              If you have any questions about this Privacy Policy, You can{" "}
              <Link href="/contact" className="text-blueprint hover:underline">
                contact us here
              </Link>
              .
            </p>
          </section>
        </section>
      </main>
      <Footer />
    </>
  );
}
